// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.17.3
// source: api/sys-exporter/SysExporter.proto

package sys_exporter

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SendStreamSnapshotsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SendStreamSnapshotsRequest) Reset() {
	*x = SendStreamSnapshotsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_sys_exporter_SysExporter_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendStreamSnapshotsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendStreamSnapshotsRequest) ProtoMessage() {}

func (x *SendStreamSnapshotsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_sys_exporter_SysExporter_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendStreamSnapshotsRequest.ProtoReflect.Descriptor instead.
func (*SendStreamSnapshotsRequest) Descriptor() ([]byte, []int) {
	return file_api_sys_exporter_SysExporter_proto_rawDescGZIP(), []int{0}
}

type SendStreamSnapshotsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Snapshot *Snapshot `protobuf:"bytes,1,opt,name=snapshot,proto3" json:"snapshot,omitempty"`
}

func (x *SendStreamSnapshotsResponse) Reset() {
	*x = SendStreamSnapshotsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_sys_exporter_SysExporter_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendStreamSnapshotsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendStreamSnapshotsResponse) ProtoMessage() {}

func (x *SendStreamSnapshotsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_sys_exporter_SysExporter_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendStreamSnapshotsResponse.ProtoReflect.Descriptor instead.
func (*SendStreamSnapshotsResponse) Descriptor() ([]byte, []int) {
	return file_api_sys_exporter_SysExporter_proto_rawDescGZIP(), []int{1}
}

func (x *SendStreamSnapshotsResponse) GetSnapshot() *Snapshot {
	if x != nil {
		return x.Snapshot
	}
	return nil
}

type Snapshot struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Timestamp   int64                 `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	LoadAverage *Snapshot_LoadAverage `protobuf:"bytes,2,opt,name=loadAverage,proto3" json:"loadAverage,omitempty"`
}

func (x *Snapshot) Reset() {
	*x = Snapshot{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_sys_exporter_SysExporter_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Snapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Snapshot) ProtoMessage() {}

func (x *Snapshot) ProtoReflect() protoreflect.Message {
	mi := &file_api_sys_exporter_SysExporter_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Snapshot.ProtoReflect.Descriptor instead.
func (*Snapshot) Descriptor() ([]byte, []int) {
	return file_api_sys_exporter_SysExporter_proto_rawDescGZIP(), []int{2}
}

func (x *Snapshot) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *Snapshot) GetLoadAverage() *Snapshot_LoadAverage {
	if x != nil {
		return x.LoadAverage
	}
	return nil
}

type Snapshot_LoadAverage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	For1Min  float32 `protobuf:"fixed32,1,opt,name=for1min,proto3" json:"for1min,omitempty"`
	For5Min  float32 `protobuf:"fixed32,2,opt,name=for5min,proto3" json:"for5min,omitempty"`
	For15Min float32 `protobuf:"fixed32,3,opt,name=for15min,proto3" json:"for15min,omitempty"`
}

func (x *Snapshot_LoadAverage) Reset() {
	*x = Snapshot_LoadAverage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_sys_exporter_SysExporter_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Snapshot_LoadAverage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Snapshot_LoadAverage) ProtoMessage() {}

func (x *Snapshot_LoadAverage) ProtoReflect() protoreflect.Message {
	mi := &file_api_sys_exporter_SysExporter_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Snapshot_LoadAverage.ProtoReflect.Descriptor instead.
func (*Snapshot_LoadAverage) Descriptor() ([]byte, []int) {
	return file_api_sys_exporter_SysExporter_proto_rawDescGZIP(), []int{2, 0}
}

func (x *Snapshot_LoadAverage) GetFor1Min() float32 {
	if x != nil {
		return x.For1Min
	}
	return 0
}

func (x *Snapshot_LoadAverage) GetFor5Min() float32 {
	if x != nil {
		return x.For5Min
	}
	return 0
}

func (x *Snapshot_LoadAverage) GetFor15Min() float32 {
	if x != nil {
		return x.For15Min
	}
	return 0
}

var File_api_sys_exporter_SysExporter_proto protoreflect.FileDescriptor

var file_api_sys_exporter_SysExporter_proto_rawDesc = []byte{
	0x0a, 0x22, 0x61, 0x70, 0x69, 0x2f, 0x73, 0x79, 0x73, 0x2d, 0x65, 0x78, 0x70, 0x6f, 0x72, 0x74,
	0x65, 0x72, 0x2f, 0x53, 0x79, 0x73, 0x45, 0x78, 0x70, 0x6f, 0x72, 0x74, 0x65, 0x72, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0c, 0x73, 0x79, 0x73, 0x5f, 0x65, 0x78, 0x70, 0x6f, 0x72, 0x74,
	0x65, 0x72, 0x1a, 0x20, 0x61, 0x70, 0x69, 0x2f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x61,
	0x70, 0x69, 0x2f, 0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0x1c, 0x0a, 0x1a, 0x53, 0x65, 0x6e, 0x64, 0x53, 0x74, 0x72, 0x65,
	0x61, 0x6d, 0x53, 0x6e, 0x61, 0x70, 0x73, 0x68, 0x6f, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x22, 0x51, 0x0a, 0x1b, 0x53, 0x65, 0x6e, 0x64, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d,
	0x53, 0x6e, 0x61, 0x70, 0x73, 0x68, 0x6f, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x32, 0x0a, 0x08, 0x73, 0x6e, 0x61, 0x70, 0x73, 0x68, 0x6f, 0x74, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x73, 0x79, 0x73, 0x5f, 0x65, 0x78, 0x70, 0x6f, 0x72, 0x74,
	0x65, 0x72, 0x2e, 0x53, 0x6e, 0x61, 0x70, 0x73, 0x68, 0x6f, 0x74, 0x52, 0x08, 0x73, 0x6e, 0x61,
	0x70, 0x73, 0x68, 0x6f, 0x74, 0x22, 0xcd, 0x01, 0x0a, 0x08, 0x53, 0x6e, 0x61, 0x70, 0x73, 0x68,
	0x6f, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70,
	0x12, 0x44, 0x0a, 0x0b, 0x6c, 0x6f, 0x61, 0x64, 0x41, 0x76, 0x65, 0x72, 0x61, 0x67, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x22, 0x2e, 0x73, 0x79, 0x73, 0x5f, 0x65, 0x78, 0x70, 0x6f,
	0x72, 0x74, 0x65, 0x72, 0x2e, 0x53, 0x6e, 0x61, 0x70, 0x73, 0x68, 0x6f, 0x74, 0x2e, 0x4c, 0x6f,
	0x61, 0x64, 0x41, 0x76, 0x65, 0x72, 0x61, 0x67, 0x65, 0x52, 0x0b, 0x6c, 0x6f, 0x61, 0x64, 0x41,
	0x76, 0x65, 0x72, 0x61, 0x67, 0x65, 0x1a, 0x5d, 0x0a, 0x0b, 0x4c, 0x6f, 0x61, 0x64, 0x41, 0x76,
	0x65, 0x72, 0x61, 0x67, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x66, 0x6f, 0x72, 0x31, 0x6d, 0x69, 0x6e,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x02, 0x52, 0x07, 0x66, 0x6f, 0x72, 0x31, 0x6d, 0x69, 0x6e, 0x12,
	0x18, 0x0a, 0x07, 0x66, 0x6f, 0x72, 0x35, 0x6d, 0x69, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x02,
	0x52, 0x07, 0x66, 0x6f, 0x72, 0x35, 0x6d, 0x69, 0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x66, 0x6f, 0x72,
	0x31, 0x35, 0x6d, 0x69, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x02, 0x52, 0x08, 0x66, 0x6f, 0x72,
	0x31, 0x35, 0x6d, 0x69, 0x6e, 0x32, 0xa3, 0x01, 0x0a, 0x0f, 0x45, 0x78, 0x70, 0x6f, 0x72, 0x74,
	0x65, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x8f, 0x01, 0x0a, 0x13, 0x53, 0x65,
	0x6e, 0x64, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x53, 0x6e, 0x61, 0x70, 0x73, 0x68, 0x6f, 0x74,
	0x73, 0x12, 0x28, 0x2e, 0x73, 0x79, 0x73, 0x5f, 0x65, 0x78, 0x70, 0x6f, 0x72, 0x74, 0x65, 0x72,
	0x2e, 0x53, 0x65, 0x6e, 0x64, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x53, 0x6e, 0x61, 0x70, 0x73,
	0x68, 0x6f, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x29, 0x2e, 0x73, 0x79,
	0x73, 0x5f, 0x65, 0x78, 0x70, 0x6f, 0x72, 0x74, 0x65, 0x72, 0x2e, 0x53, 0x65, 0x6e, 0x64, 0x53,
	0x74, 0x72, 0x65, 0x61, 0x6d, 0x53, 0x6e, 0x61, 0x70, 0x73, 0x68, 0x6f, 0x74, 0x73, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x21, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x1b, 0x22, 0x16,
	0x2f, 0x73, 0x6e, 0x61, 0x70, 0x73, 0x68, 0x6f, 0x74, 0x73, 0x2f, 0x73, 0x65, 0x6e, 0x64, 0x2d,
	0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x3a, 0x01, 0x2a, 0x30, 0x01, 0x42, 0x30, 0x5a, 0x2e, 0x67,
	0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x68, 0x69, 0x68, 0x6f, 0x61, 0x6b,
	0x2f, 0x6f, 0x74, 0x75, 0x73, 0x2d, 0x63, 0x6f, 0x75, 0x72, 0x73, 0x65, 0x2d, 0x68, 0x77, 0x73,
	0x2f, 0x73, 0x79, 0x73, 0x2d, 0x65, 0x78, 0x70, 0x6f, 0x72, 0x74, 0x65, 0x72, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_sys_exporter_SysExporter_proto_rawDescOnce sync.Once
	file_api_sys_exporter_SysExporter_proto_rawDescData = file_api_sys_exporter_SysExporter_proto_rawDesc
)

func file_api_sys_exporter_SysExporter_proto_rawDescGZIP() []byte {
	file_api_sys_exporter_SysExporter_proto_rawDescOnce.Do(func() {
		file_api_sys_exporter_SysExporter_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_sys_exporter_SysExporter_proto_rawDescData)
	})
	return file_api_sys_exporter_SysExporter_proto_rawDescData
}

var file_api_sys_exporter_SysExporter_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_api_sys_exporter_SysExporter_proto_goTypes = []interface{}{
	(*SendStreamSnapshotsRequest)(nil),  // 0: sys_exporter.SendStreamSnapshotsRequest
	(*SendStreamSnapshotsResponse)(nil), // 1: sys_exporter.SendStreamSnapshotsResponse
	(*Snapshot)(nil),                    // 2: sys_exporter.Snapshot
	(*Snapshot_LoadAverage)(nil),        // 3: sys_exporter.Snapshot.LoadAverage
}
var file_api_sys_exporter_SysExporter_proto_depIdxs = []int32{
	2, // 0: sys_exporter.SendStreamSnapshotsResponse.snapshot:type_name -> sys_exporter.Snapshot
	3, // 1: sys_exporter.Snapshot.loadAverage:type_name -> sys_exporter.Snapshot.LoadAverage
	0, // 2: sys_exporter.ExporterService.SendStreamSnapshots:input_type -> sys_exporter.SendStreamSnapshotsRequest
	1, // 3: sys_exporter.ExporterService.SendStreamSnapshots:output_type -> sys_exporter.SendStreamSnapshotsResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_api_sys_exporter_SysExporter_proto_init() }
func file_api_sys_exporter_SysExporter_proto_init() {
	if File_api_sys_exporter_SysExporter_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_sys_exporter_SysExporter_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendStreamSnapshotsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_sys_exporter_SysExporter_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendStreamSnapshotsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_sys_exporter_SysExporter_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Snapshot); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_sys_exporter_SysExporter_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Snapshot_LoadAverage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_sys_exporter_SysExporter_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_sys_exporter_SysExporter_proto_goTypes,
		DependencyIndexes: file_api_sys_exporter_SysExporter_proto_depIdxs,
		MessageInfos:      file_api_sys_exporter_SysExporter_proto_msgTypes,
	}.Build()
	File_api_sys_exporter_SysExporter_proto = out.File
	file_api_sys_exporter_SysExporter_proto_rawDesc = nil
	file_api_sys_exporter_SysExporter_proto_goTypes = nil
	file_api_sys_exporter_SysExporter_proto_depIdxs = nil
}
