// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.17.3
// source: api/sys-exporter/SysExporter.proto

package sys_exporter

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SendStreamSnapshotsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SendStreamSnapshotsRequest) Reset() {
	*x = SendStreamSnapshotsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_sys_exporter_SysExporter_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendStreamSnapshotsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendStreamSnapshotsRequest) ProtoMessage() {}

func (x *SendStreamSnapshotsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_sys_exporter_SysExporter_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendStreamSnapshotsRequest.ProtoReflect.Descriptor instead.
func (*SendStreamSnapshotsRequest) Descriptor() ([]byte, []int) {
	return file_api_sys_exporter_SysExporter_proto_rawDescGZIP(), []int{0}
}

type SendStreamSnapshotsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Snapshot *Snapshot `protobuf:"bytes,1,opt,name=snapshot,proto3" json:"snapshot,omitempty"`
}

func (x *SendStreamSnapshotsResponse) Reset() {
	*x = SendStreamSnapshotsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_sys_exporter_SysExporter_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendStreamSnapshotsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendStreamSnapshotsResponse) ProtoMessage() {}

func (x *SendStreamSnapshotsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_sys_exporter_SysExporter_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendStreamSnapshotsResponse.ProtoReflect.Descriptor instead.
func (*SendStreamSnapshotsResponse) Descriptor() ([]byte, []int) {
	return file_api_sys_exporter_SysExporter_proto_rawDescGZIP(), []int{1}
}

func (x *SendStreamSnapshotsResponse) GetSnapshot() *Snapshot {
	if x != nil {
		return x.Snapshot
	}
	return nil
}

type Snapshot struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Timestamp         int64                       `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	LoadAverage       *Snapshot_LoadAverage       `protobuf:"bytes,2,opt,name=loadAverage,proto3" json:"loadAverage,omitempty"`
	CpuUsage          *Snapshot_CpuUsage          `protobuf:"bytes,3,opt,name=cpuUsage,proto3" json:"cpuUsage,omitempty"`
	DiskUsage         *Snapshot_DiskUsage         `protobuf:"bytes,4,opt,name=diskUsage,proto3" json:"diskUsage,omitempty"`
	NetworkTopTalkers *Snapshot_NetworkTopTalkers `protobuf:"bytes,5,opt,name=networkTopTalkers,proto3" json:"networkTopTalkers,omitempty"`
	FileSystemInfo    *Snapshot_FileSystemInfo    `protobuf:"bytes,6,opt,name=fileSystemInfo,proto3" json:"fileSystemInfo,omitempty"`
}

func (x *Snapshot) Reset() {
	*x = Snapshot{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_sys_exporter_SysExporter_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Snapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Snapshot) ProtoMessage() {}

func (x *Snapshot) ProtoReflect() protoreflect.Message {
	mi := &file_api_sys_exporter_SysExporter_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Snapshot.ProtoReflect.Descriptor instead.
func (*Snapshot) Descriptor() ([]byte, []int) {
	return file_api_sys_exporter_SysExporter_proto_rawDescGZIP(), []int{2}
}

func (x *Snapshot) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *Snapshot) GetLoadAverage() *Snapshot_LoadAverage {
	if x != nil {
		return x.LoadAverage
	}
	return nil
}

func (x *Snapshot) GetCpuUsage() *Snapshot_CpuUsage {
	if x != nil {
		return x.CpuUsage
	}
	return nil
}

func (x *Snapshot) GetDiskUsage() *Snapshot_DiskUsage {
	if x != nil {
		return x.DiskUsage
	}
	return nil
}

func (x *Snapshot) GetNetworkTopTalkers() *Snapshot_NetworkTopTalkers {
	if x != nil {
		return x.NetworkTopTalkers
	}
	return nil
}

func (x *Snapshot) GetFileSystemInfo() *Snapshot_FileSystemInfo {
	if x != nil {
		return x.FileSystemInfo
	}
	return nil
}

type Snapshot_LoadAverage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	For1Min     float32 `protobuf:"fixed32,1,opt,name=for1min,proto3" json:"for1min,omitempty"`
	For5Min     float32 `protobuf:"fixed32,2,opt,name=for5min,proto3" json:"for5min,omitempty"`
	For15Min    float32 `protobuf:"fixed32,3,opt,name=for15min,proto3" json:"for15min,omitempty"`
	CpuUsageWin float32 `protobuf:"fixed32,4,opt,name=cpu_usage_win,json=cpuUsageWin,proto3" json:"cpu_usage_win,omitempty"`
}

func (x *Snapshot_LoadAverage) Reset() {
	*x = Snapshot_LoadAverage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_sys_exporter_SysExporter_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Snapshot_LoadAverage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Snapshot_LoadAverage) ProtoMessage() {}

func (x *Snapshot_LoadAverage) ProtoReflect() protoreflect.Message {
	mi := &file_api_sys_exporter_SysExporter_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Snapshot_LoadAverage.ProtoReflect.Descriptor instead.
func (*Snapshot_LoadAverage) Descriptor() ([]byte, []int) {
	return file_api_sys_exporter_SysExporter_proto_rawDescGZIP(), []int{2, 0}
}

func (x *Snapshot_LoadAverage) GetFor1Min() float32 {
	if x != nil {
		return x.For1Min
	}
	return 0
}

func (x *Snapshot_LoadAverage) GetFor5Min() float32 {
	if x != nil {
		return x.For5Min
	}
	return 0
}

func (x *Snapshot_LoadAverage) GetFor15Min() float32 {
	if x != nil {
		return x.For15Min
	}
	return 0
}

func (x *Snapshot_LoadAverage) GetCpuUsageWin() float32 {
	if x != nil {
		return x.CpuUsageWin
	}
	return 0
}

type Snapshot_CpuUsage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	User float32 `protobuf:"fixed32,1,opt,name=user,proto3" json:"user,omitempty"`
	Sys  float32 `protobuf:"fixed32,2,opt,name=sys,proto3" json:"sys,omitempty"`
	Idle float32 `protobuf:"fixed32,3,opt,name=idle,proto3" json:"idle,omitempty"`
}

func (x *Snapshot_CpuUsage) Reset() {
	*x = Snapshot_CpuUsage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_sys_exporter_SysExporter_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Snapshot_CpuUsage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Snapshot_CpuUsage) ProtoMessage() {}

func (x *Snapshot_CpuUsage) ProtoReflect() protoreflect.Message {
	mi := &file_api_sys_exporter_SysExporter_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Snapshot_CpuUsage.ProtoReflect.Descriptor instead.
func (*Snapshot_CpuUsage) Descriptor() ([]byte, []int) {
	return file_api_sys_exporter_SysExporter_proto_rawDescGZIP(), []int{2, 1}
}

func (x *Snapshot_CpuUsage) GetUser() float32 {
	if x != nil {
		return x.User
	}
	return 0
}

func (x *Snapshot_CpuUsage) GetSys() float32 {
	if x != nil {
		return x.Sys
	}
	return 0
}

func (x *Snapshot_CpuUsage) GetIdle() float32 {
	if x != nil {
		return x.Idle
	}
	return 0
}

type Snapshot_DiskUsage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	KbPerTransfer      float32 `protobuf:"fixed32,1,opt,name=kbPerTransfer,proto3" json:"kbPerTransfer,omitempty"`
	MbPerSecond        float32 `protobuf:"fixed32,2,opt,name=mbPerSecond,proto3" json:"mbPerSecond,omitempty"`
	TransfersPerSecond int64   `protobuf:"varint,3,opt,name=transfersPerSecond,proto3" json:"transfersPerSecond,omitempty"`
}

func (x *Snapshot_DiskUsage) Reset() {
	*x = Snapshot_DiskUsage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_sys_exporter_SysExporter_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Snapshot_DiskUsage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Snapshot_DiskUsage) ProtoMessage() {}

func (x *Snapshot_DiskUsage) ProtoReflect() protoreflect.Message {
	mi := &file_api_sys_exporter_SysExporter_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Snapshot_DiskUsage.ProtoReflect.Descriptor instead.
func (*Snapshot_DiskUsage) Descriptor() ([]byte, []int) {
	return file_api_sys_exporter_SysExporter_proto_rawDescGZIP(), []int{2, 2}
}

func (x *Snapshot_DiskUsage) GetKbPerTransfer() float32 {
	if x != nil {
		return x.KbPerTransfer
	}
	return 0
}

func (x *Snapshot_DiskUsage) GetMbPerSecond() float32 {
	if x != nil {
		return x.MbPerSecond
	}
	return 0
}

func (x *Snapshot_DiskUsage) GetTransfersPerSecond() int64 {
	if x != nil {
		return x.TransfersPerSecond
	}
	return 0
}

type Snapshot_NetworkTopTalkers struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ByBytesIn  []*Snapshot_NetworkTopTalkers_NetworkTalker `protobuf:"bytes,1,rep,name=byBytesIn,proto3" json:"byBytesIn,omitempty"`
	ByBytesOut []*Snapshot_NetworkTopTalkers_NetworkTalker `protobuf:"bytes,2,rep,name=byBytesOut,proto3" json:"byBytesOut,omitempty"`
}

func (x *Snapshot_NetworkTopTalkers) Reset() {
	*x = Snapshot_NetworkTopTalkers{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_sys_exporter_SysExporter_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Snapshot_NetworkTopTalkers) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Snapshot_NetworkTopTalkers) ProtoMessage() {}

func (x *Snapshot_NetworkTopTalkers) ProtoReflect() protoreflect.Message {
	mi := &file_api_sys_exporter_SysExporter_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Snapshot_NetworkTopTalkers.ProtoReflect.Descriptor instead.
func (*Snapshot_NetworkTopTalkers) Descriptor() ([]byte, []int) {
	return file_api_sys_exporter_SysExporter_proto_rawDescGZIP(), []int{2, 3}
}

func (x *Snapshot_NetworkTopTalkers) GetByBytesIn() []*Snapshot_NetworkTopTalkers_NetworkTalker {
	if x != nil {
		return x.ByBytesIn
	}
	return nil
}

func (x *Snapshot_NetworkTopTalkers) GetByBytesOut() []*Snapshot_NetworkTopTalkers_NetworkTalker {
	if x != nil {
		return x.ByBytesOut
	}
	return nil
}

type Snapshot_FileSystemInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FileSystem []*Snapshot_FileSystemInfo_FileSystem `protobuf:"bytes,1,rep,name=fileSystem,proto3" json:"fileSystem,omitempty"`
}

func (x *Snapshot_FileSystemInfo) Reset() {
	*x = Snapshot_FileSystemInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_sys_exporter_SysExporter_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Snapshot_FileSystemInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Snapshot_FileSystemInfo) ProtoMessage() {}

func (x *Snapshot_FileSystemInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_sys_exporter_SysExporter_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Snapshot_FileSystemInfo.ProtoReflect.Descriptor instead.
func (*Snapshot_FileSystemInfo) Descriptor() ([]byte, []int) {
	return file_api_sys_exporter_SysExporter_proto_rawDescGZIP(), []int{2, 4}
}

func (x *Snapshot_FileSystemInfo) GetFileSystem() []*Snapshot_FileSystemInfo_FileSystem {
	if x != nil {
		return x.FileSystem
	}
	return nil
}

type Snapshot_NetworkTopTalkers_NetworkTalker struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name     string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Pid      int64  `protobuf:"varint,2,opt,name=pid,proto3" json:"pid,omitempty"`
	BytesIn  int64  `protobuf:"varint,3,opt,name=bytesIn,proto3" json:"bytesIn,omitempty"`
	BytesOut int64  `protobuf:"varint,4,opt,name=bytesOut,proto3" json:"bytesOut,omitempty"`
}

func (x *Snapshot_NetworkTopTalkers_NetworkTalker) Reset() {
	*x = Snapshot_NetworkTopTalkers_NetworkTalker{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_sys_exporter_SysExporter_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Snapshot_NetworkTopTalkers_NetworkTalker) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Snapshot_NetworkTopTalkers_NetworkTalker) ProtoMessage() {}

func (x *Snapshot_NetworkTopTalkers_NetworkTalker) ProtoReflect() protoreflect.Message {
	mi := &file_api_sys_exporter_SysExporter_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Snapshot_NetworkTopTalkers_NetworkTalker.ProtoReflect.Descriptor instead.
func (*Snapshot_NetworkTopTalkers_NetworkTalker) Descriptor() ([]byte, []int) {
	return file_api_sys_exporter_SysExporter_proto_rawDescGZIP(), []int{2, 3, 0}
}

func (x *Snapshot_NetworkTopTalkers_NetworkTalker) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Snapshot_NetworkTopTalkers_NetworkTalker) GetPid() int64 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *Snapshot_NetworkTopTalkers_NetworkTalker) GetBytesIn() int64 {
	if x != nil {
		return x.BytesIn
	}
	return 0
}

func (x *Snapshot_NetworkTopTalkers_NetworkTalker) GetBytesOut() int64 {
	if x != nil {
		return x.BytesOut
	}
	return 0
}

type Snapshot_FileSystemInfo_FileSystem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FileSystem string                                                   `protobuf:"bytes,1,opt,name=fileSystem,proto3" json:"fileSystem,omitempty"`
	MemoryInfo *Snapshot_FileSystemInfo_FileSystem_FileSystemMemoryInfo `protobuf:"bytes,2,opt,name=memoryInfo,proto3" json:"memoryInfo,omitempty"`
	InodeInfo  *Snapshot_FileSystemInfo_FileSystem_FileSystemInodeInfo  `protobuf:"bytes,3,opt,name=inodeInfo,proto3" json:"inodeInfo,omitempty"`
	MountedOn  string                                                   `protobuf:"bytes,4,opt,name=mountedOn,proto3" json:"mountedOn,omitempty"`
}

func (x *Snapshot_FileSystemInfo_FileSystem) Reset() {
	*x = Snapshot_FileSystemInfo_FileSystem{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_sys_exporter_SysExporter_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Snapshot_FileSystemInfo_FileSystem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Snapshot_FileSystemInfo_FileSystem) ProtoMessage() {}

func (x *Snapshot_FileSystemInfo_FileSystem) ProtoReflect() protoreflect.Message {
	mi := &file_api_sys_exporter_SysExporter_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Snapshot_FileSystemInfo_FileSystem.ProtoReflect.Descriptor instead.
func (*Snapshot_FileSystemInfo_FileSystem) Descriptor() ([]byte, []int) {
	return file_api_sys_exporter_SysExporter_proto_rawDescGZIP(), []int{2, 4, 0}
}

func (x *Snapshot_FileSystemInfo_FileSystem) GetFileSystem() string {
	if x != nil {
		return x.FileSystem
	}
	return ""
}

func (x *Snapshot_FileSystemInfo_FileSystem) GetMemoryInfo() *Snapshot_FileSystemInfo_FileSystem_FileSystemMemoryInfo {
	if x != nil {
		return x.MemoryInfo
	}
	return nil
}

func (x *Snapshot_FileSystemInfo_FileSystem) GetInodeInfo() *Snapshot_FileSystemInfo_FileSystem_FileSystemInodeInfo {
	if x != nil {
		return x.InodeInfo
	}
	return nil
}

func (x *Snapshot_FileSystemInfo_FileSystem) GetMountedOn() string {
	if x != nil {
		return x.MountedOn
	}
	return ""
}

type Snapshot_FileSystemInfo_FileSystem_FileSystemMemoryInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SizeBytes       int64   `protobuf:"varint,1,opt,name=sizeBytes,proto3" json:"sizeBytes,omitempty"`
	UsedBytes       int64   `protobuf:"varint,2,opt,name=usedBytes,proto3" json:"usedBytes,omitempty"`
	AvailableBytes  int64   `protobuf:"varint,3,opt,name=availableBytes,proto3" json:"availableBytes,omitempty"`
	CapacityPercent float32 `protobuf:"fixed32,4,opt,name=capacityPercent,proto3" json:"capacityPercent,omitempty"`
}

func (x *Snapshot_FileSystemInfo_FileSystem_FileSystemMemoryInfo) Reset() {
	*x = Snapshot_FileSystemInfo_FileSystem_FileSystemMemoryInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_sys_exporter_SysExporter_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Snapshot_FileSystemInfo_FileSystem_FileSystemMemoryInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Snapshot_FileSystemInfo_FileSystem_FileSystemMemoryInfo) ProtoMessage() {}

func (x *Snapshot_FileSystemInfo_FileSystem_FileSystemMemoryInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_sys_exporter_SysExporter_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Snapshot_FileSystemInfo_FileSystem_FileSystemMemoryInfo.ProtoReflect.Descriptor instead.
func (*Snapshot_FileSystemInfo_FileSystem_FileSystemMemoryInfo) Descriptor() ([]byte, []int) {
	return file_api_sys_exporter_SysExporter_proto_rawDescGZIP(), []int{2, 4, 0, 0}
}

func (x *Snapshot_FileSystemInfo_FileSystem_FileSystemMemoryInfo) GetSizeBytes() int64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

func (x *Snapshot_FileSystemInfo_FileSystem_FileSystemMemoryInfo) GetUsedBytes() int64 {
	if x != nil {
		return x.UsedBytes
	}
	return 0
}

func (x *Snapshot_FileSystemInfo_FileSystem_FileSystemMemoryInfo) GetAvailableBytes() int64 {
	if x != nil {
		return x.AvailableBytes
	}
	return 0
}

func (x *Snapshot_FileSystemInfo_FileSystem_FileSystemMemoryInfo) GetCapacityPercent() float32 {
	if x != nil {
		return x.CapacityPercent
	}
	return 0
}

type Snapshot_FileSystemInfo_FileSystem_FileSystemInodeInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	InodeUsed        int64   `protobuf:"varint,1,opt,name=inodeUsed,proto3" json:"inodeUsed,omitempty"`
	InodeFree        int64   `protobuf:"varint,2,opt,name=inodeFree,proto3" json:"inodeFree,omitempty"`
	InodeUsedPercent float32 `protobuf:"fixed32,3,opt,name=inodeUsedPercent,proto3" json:"inodeUsedPercent,omitempty"`
}

func (x *Snapshot_FileSystemInfo_FileSystem_FileSystemInodeInfo) Reset() {
	*x = Snapshot_FileSystemInfo_FileSystem_FileSystemInodeInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_sys_exporter_SysExporter_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Snapshot_FileSystemInfo_FileSystem_FileSystemInodeInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Snapshot_FileSystemInfo_FileSystem_FileSystemInodeInfo) ProtoMessage() {}

func (x *Snapshot_FileSystemInfo_FileSystem_FileSystemInodeInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_sys_exporter_SysExporter_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Snapshot_FileSystemInfo_FileSystem_FileSystemInodeInfo.ProtoReflect.Descriptor instead.
func (*Snapshot_FileSystemInfo_FileSystem_FileSystemInodeInfo) Descriptor() ([]byte, []int) {
	return file_api_sys_exporter_SysExporter_proto_rawDescGZIP(), []int{2, 4, 0, 1}
}

func (x *Snapshot_FileSystemInfo_FileSystem_FileSystemInodeInfo) GetInodeUsed() int64 {
	if x != nil {
		return x.InodeUsed
	}
	return 0
}

func (x *Snapshot_FileSystemInfo_FileSystem_FileSystemInodeInfo) GetInodeFree() int64 {
	if x != nil {
		return x.InodeFree
	}
	return 0
}

func (x *Snapshot_FileSystemInfo_FileSystem_FileSystemInodeInfo) GetInodeUsedPercent() float32 {
	if x != nil {
		return x.InodeUsedPercent
	}
	return 0
}

var File_api_sys_exporter_SysExporter_proto protoreflect.FileDescriptor

var file_api_sys_exporter_SysExporter_proto_rawDesc = []byte{
	0x0a, 0x22, 0x61, 0x70, 0x69, 0x2f, 0x73, 0x79, 0x73, 0x2d, 0x65, 0x78, 0x70, 0x6f, 0x72, 0x74,
	0x65, 0x72, 0x2f, 0x53, 0x79, 0x73, 0x45, 0x78, 0x70, 0x6f, 0x72, 0x74, 0x65, 0x72, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0c, 0x73, 0x79, 0x73, 0x5f, 0x65, 0x78, 0x70, 0x6f, 0x72, 0x74,
	0x65, 0x72, 0x1a, 0x20, 0x61, 0x70, 0x69, 0x2f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x61,
	0x70, 0x69, 0x2f, 0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0x1c, 0x0a, 0x1a, 0x53, 0x65, 0x6e, 0x64, 0x53, 0x74, 0x72, 0x65,
	0x61, 0x6d, 0x53, 0x6e, 0x61, 0x70, 0x73, 0x68, 0x6f, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x22, 0x51, 0x0a, 0x1b, 0x53, 0x65, 0x6e, 0x64, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d,
	0x53, 0x6e, 0x61, 0x70, 0x73, 0x68, 0x6f, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x32, 0x0a, 0x08, 0x73, 0x6e, 0x61, 0x70, 0x73, 0x68, 0x6f, 0x74, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x73, 0x79, 0x73, 0x5f, 0x65, 0x78, 0x70, 0x6f, 0x72, 0x74,
	0x65, 0x72, 0x2e, 0x53, 0x6e, 0x61, 0x70, 0x73, 0x68, 0x6f, 0x74, 0x52, 0x08, 0x73, 0x6e, 0x61,
	0x70, 0x73, 0x68, 0x6f, 0x74, 0x22, 0xb6, 0x0d, 0x0a, 0x08, 0x53, 0x6e, 0x61, 0x70, 0x73, 0x68,
	0x6f, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70,
	0x12, 0x44, 0x0a, 0x0b, 0x6c, 0x6f, 0x61, 0x64, 0x41, 0x76, 0x65, 0x72, 0x61, 0x67, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x22, 0x2e, 0x73, 0x79, 0x73, 0x5f, 0x65, 0x78, 0x70, 0x6f,
	0x72, 0x74, 0x65, 0x72, 0x2e, 0x53, 0x6e, 0x61, 0x70, 0x73, 0x68, 0x6f, 0x74, 0x2e, 0x4c, 0x6f,
	0x61, 0x64, 0x41, 0x76, 0x65, 0x72, 0x61, 0x67, 0x65, 0x52, 0x0b, 0x6c, 0x6f, 0x61, 0x64, 0x41,
	0x76, 0x65, 0x72, 0x61, 0x67, 0x65, 0x12, 0x3b, 0x0a, 0x08, 0x63, 0x70, 0x75, 0x55, 0x73, 0x61,
	0x67, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x73, 0x79, 0x73, 0x5f, 0x65,
	0x78, 0x70, 0x6f, 0x72, 0x74, 0x65, 0x72, 0x2e, 0x53, 0x6e, 0x61, 0x70, 0x73, 0x68, 0x6f, 0x74,
	0x2e, 0x43, 0x70, 0x75, 0x55, 0x73, 0x61, 0x67, 0x65, 0x52, 0x08, 0x63, 0x70, 0x75, 0x55, 0x73,
	0x61, 0x67, 0x65, 0x12, 0x3e, 0x0a, 0x09, 0x64, 0x69, 0x73, 0x6b, 0x55, 0x73, 0x61, 0x67, 0x65,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x73, 0x79, 0x73, 0x5f, 0x65, 0x78, 0x70,
	0x6f, 0x72, 0x74, 0x65, 0x72, 0x2e, 0x53, 0x6e, 0x61, 0x70, 0x73, 0x68, 0x6f, 0x74, 0x2e, 0x44,
	0x69, 0x73, 0x6b, 0x55, 0x73, 0x61, 0x67, 0x65, 0x52, 0x09, 0x64, 0x69, 0x73, 0x6b, 0x55, 0x73,
	0x61, 0x67, 0x65, 0x12, 0x56, 0x0a, 0x11, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x54, 0x6f,
	0x70, 0x54, 0x61, 0x6c, 0x6b, 0x65, 0x72, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x28,
	0x2e, 0x73, 0x79, 0x73, 0x5f, 0x65, 0x78, 0x70, 0x6f, 0x72, 0x74, 0x65, 0x72, 0x2e, 0x53, 0x6e,
	0x61, 0x70, 0x73, 0x68, 0x6f, 0x74, 0x2e, 0x4e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x54, 0x6f,
	0x70, 0x54, 0x61, 0x6c, 0x6b, 0x65, 0x72, 0x73, 0x52, 0x11, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72,
	0x6b, 0x54, 0x6f, 0x70, 0x54, 0x61, 0x6c, 0x6b, 0x65, 0x72, 0x73, 0x12, 0x4d, 0x0a, 0x0e, 0x66,
	0x69, 0x6c, 0x65, 0x53, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x49, 0x6e, 0x66, 0x6f, 0x18, 0x06, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x25, 0x2e, 0x73, 0x79, 0x73, 0x5f, 0x65, 0x78, 0x70, 0x6f, 0x72, 0x74,
	0x65, 0x72, 0x2e, 0x53, 0x6e, 0x61, 0x70, 0x73, 0x68, 0x6f, 0x74, 0x2e, 0x46, 0x69, 0x6c, 0x65,
	0x53, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x0e, 0x66, 0x69, 0x6c, 0x65,
	0x53, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x49, 0x6e, 0x66, 0x6f, 0x1a, 0x81, 0x01, 0x0a, 0x0b, 0x4c,
	0x6f, 0x61, 0x64, 0x41, 0x76, 0x65, 0x72, 0x61, 0x67, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x66, 0x6f,
	0x72, 0x31, 0x6d, 0x69, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x02, 0x52, 0x07, 0x66, 0x6f, 0x72,
	0x31, 0x6d, 0x69, 0x6e, 0x12, 0x18, 0x0a, 0x07, 0x66, 0x6f, 0x72, 0x35, 0x6d, 0x69, 0x6e, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x02, 0x52, 0x07, 0x66, 0x6f, 0x72, 0x35, 0x6d, 0x69, 0x6e, 0x12, 0x1a,
	0x0a, 0x08, 0x66, 0x6f, 0x72, 0x31, 0x35, 0x6d, 0x69, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x02,
	0x52, 0x08, 0x66, 0x6f, 0x72, 0x31, 0x35, 0x6d, 0x69, 0x6e, 0x12, 0x22, 0x0a, 0x0d, 0x63, 0x70,
	0x75, 0x5f, 0x75, 0x73, 0x61, 0x67, 0x65, 0x5f, 0x77, 0x69, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x02, 0x52, 0x0b, 0x63, 0x70, 0x75, 0x55, 0x73, 0x61, 0x67, 0x65, 0x57, 0x69, 0x6e, 0x1a, 0x44,
	0x0a, 0x08, 0x43, 0x70, 0x75, 0x55, 0x73, 0x61, 0x67, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x73,
	0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x02, 0x52, 0x04, 0x75, 0x73, 0x65, 0x72, 0x12, 0x10,
	0x0a, 0x03, 0x73, 0x79, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x02, 0x52, 0x03, 0x73, 0x79, 0x73,
	0x12, 0x12, 0x0a, 0x04, 0x69, 0x64, 0x6c, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x02, 0x52, 0x04,
	0x69, 0x64, 0x6c, 0x65, 0x1a, 0x83, 0x01, 0x0a, 0x09, 0x44, 0x69, 0x73, 0x6b, 0x55, 0x73, 0x61,
	0x67, 0x65, 0x12, 0x24, 0x0a, 0x0d, 0x6b, 0x62, 0x50, 0x65, 0x72, 0x54, 0x72, 0x61, 0x6e, 0x73,
	0x66, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x02, 0x52, 0x0d, 0x6b, 0x62, 0x50, 0x65, 0x72,
	0x54, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x65, 0x72, 0x12, 0x20, 0x0a, 0x0b, 0x6d, 0x62, 0x50, 0x65,
	0x72, 0x53, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x02, 0x52, 0x0b, 0x6d,
	0x62, 0x50, 0x65, 0x72, 0x53, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x12, 0x2e, 0x0a, 0x12, 0x74, 0x72,
	0x61, 0x6e, 0x73, 0x66, 0x65, 0x72, 0x73, 0x50, 0x65, 0x72, 0x53, 0x65, 0x63, 0x6f, 0x6e, 0x64,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x12, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x65, 0x72,
	0x73, 0x50, 0x65, 0x72, 0x53, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x1a, 0xae, 0x02, 0x0a, 0x11, 0x4e,
	0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x54, 0x6f, 0x70, 0x54, 0x61, 0x6c, 0x6b, 0x65, 0x72, 0x73,
	0x12, 0x54, 0x0a, 0x09, 0x62, 0x79, 0x42, 0x79, 0x74, 0x65, 0x73, 0x49, 0x6e, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x36, 0x2e, 0x73, 0x79, 0x73, 0x5f, 0x65, 0x78, 0x70, 0x6f, 0x72, 0x74,
	0x65, 0x72, 0x2e, 0x53, 0x6e, 0x61, 0x70, 0x73, 0x68, 0x6f, 0x74, 0x2e, 0x4e, 0x65, 0x74, 0x77,
	0x6f, 0x72, 0x6b, 0x54, 0x6f, 0x70, 0x54, 0x61, 0x6c, 0x6b, 0x65, 0x72, 0x73, 0x2e, 0x4e, 0x65,
	0x74, 0x77, 0x6f, 0x72, 0x6b, 0x54, 0x61, 0x6c, 0x6b, 0x65, 0x72, 0x52, 0x09, 0x62, 0x79, 0x42,
	0x79, 0x74, 0x65, 0x73, 0x49, 0x6e, 0x12, 0x56, 0x0a, 0x0a, 0x62, 0x79, 0x42, 0x79, 0x74, 0x65,
	0x73, 0x4f, 0x75, 0x74, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x36, 0x2e, 0x73, 0x79, 0x73,
	0x5f, 0x65, 0x78, 0x70, 0x6f, 0x72, 0x74, 0x65, 0x72, 0x2e, 0x53, 0x6e, 0x61, 0x70, 0x73, 0x68,
	0x6f, 0x74, 0x2e, 0x4e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x54, 0x6f, 0x70, 0x54, 0x61, 0x6c,
	0x6b, 0x65, 0x72, 0x73, 0x2e, 0x4e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x54, 0x61, 0x6c, 0x6b,
	0x65, 0x72, 0x52, 0x0a, 0x62, 0x79, 0x42, 0x79, 0x74, 0x65, 0x73, 0x4f, 0x75, 0x74, 0x1a, 0x6b,
	0x0a, 0x0d, 0x4e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x54, 0x61, 0x6c, 0x6b, 0x65, 0x72, 0x12,
	0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x70, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x03, 0x70, 0x69, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x62, 0x79, 0x74, 0x65, 0x73, 0x49, 0x6e,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x62, 0x79, 0x74, 0x65, 0x73, 0x49, 0x6e, 0x12,
	0x1a, 0x0a, 0x08, 0x62, 0x79, 0x74, 0x65, 0x73, 0x4f, 0x75, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x08, 0x62, 0x79, 0x74, 0x65, 0x73, 0x4f, 0x75, 0x74, 0x1a, 0xa0, 0x05, 0x0a, 0x0e,
	0x46, 0x69, 0x6c, 0x65, 0x53, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x50,
	0x0a, 0x0a, 0x66, 0x69, 0x6c, 0x65, 0x53, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x30, 0x2e, 0x73, 0x79, 0x73, 0x5f, 0x65, 0x78, 0x70, 0x6f, 0x72, 0x74, 0x65,
	0x72, 0x2e, 0x53, 0x6e, 0x61, 0x70, 0x73, 0x68, 0x6f, 0x74, 0x2e, 0x46, 0x69, 0x6c, 0x65, 0x53,
	0x79, 0x73, 0x74, 0x65, 0x6d, 0x49, 0x6e, 0x66, 0x6f, 0x2e, 0x46, 0x69, 0x6c, 0x65, 0x53, 0x79,
	0x73, 0x74, 0x65, 0x6d, 0x52, 0x0a, 0x66, 0x69, 0x6c, 0x65, 0x53, 0x79, 0x73, 0x74, 0x65, 0x6d,
	0x1a, 0xbb, 0x04, 0x0a, 0x0a, 0x46, 0x69, 0x6c, 0x65, 0x53, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x12,
	0x1e, 0x0a, 0x0a, 0x66, 0x69, 0x6c, 0x65, 0x53, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0a, 0x66, 0x69, 0x6c, 0x65, 0x53, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x12,
	0x65, 0x0a, 0x0a, 0x6d, 0x65, 0x6d, 0x6f, 0x72, 0x79, 0x49, 0x6e, 0x66, 0x6f, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x45, 0x2e, 0x73, 0x79, 0x73, 0x5f, 0x65, 0x78, 0x70, 0x6f, 0x72, 0x74,
	0x65, 0x72, 0x2e, 0x53, 0x6e, 0x61, 0x70, 0x73, 0x68, 0x6f, 0x74, 0x2e, 0x46, 0x69, 0x6c, 0x65,
	0x53, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x49, 0x6e, 0x66, 0x6f, 0x2e, 0x46, 0x69, 0x6c, 0x65, 0x53,
	0x79, 0x73, 0x74, 0x65, 0x6d, 0x2e, 0x46, 0x69, 0x6c, 0x65, 0x53, 0x79, 0x73, 0x74, 0x65, 0x6d,
	0x4d, 0x65, 0x6d, 0x6f, 0x72, 0x79, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x0a, 0x6d, 0x65, 0x6d, 0x6f,
	0x72, 0x79, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x62, 0x0a, 0x09, 0x69, 0x6e, 0x6f, 0x64, 0x65, 0x49,
	0x6e, 0x66, 0x6f, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x44, 0x2e, 0x73, 0x79, 0x73, 0x5f,
	0x65, 0x78, 0x70, 0x6f, 0x72, 0x74, 0x65, 0x72, 0x2e, 0x53, 0x6e, 0x61, 0x70, 0x73, 0x68, 0x6f,
	0x74, 0x2e, 0x46, 0x69, 0x6c, 0x65, 0x53, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x49, 0x6e, 0x66, 0x6f,
	0x2e, 0x46, 0x69, 0x6c, 0x65, 0x53, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x2e, 0x46, 0x69, 0x6c, 0x65,
	0x53, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x49, 0x6e, 0x6f, 0x64, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52,
	0x09, 0x69, 0x6e, 0x6f, 0x64, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x1c, 0x0a, 0x09, 0x6d, 0x6f,
	0x75, 0x6e, 0x74, 0x65, 0x64, 0x4f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6d,
	0x6f, 0x75, 0x6e, 0x74, 0x65, 0x64, 0x4f, 0x6e, 0x1a, 0xa4, 0x01, 0x0a, 0x14, 0x46, 0x69, 0x6c,
	0x65, 0x53, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x4d, 0x65, 0x6d, 0x6f, 0x72, 0x79, 0x49, 0x6e, 0x66,
	0x6f, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x69, 0x7a, 0x65, 0x42, 0x79, 0x74, 0x65, 0x73, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x73, 0x69, 0x7a, 0x65, 0x42, 0x79, 0x74, 0x65, 0x73, 0x12,
	0x1c, 0x0a, 0x09, 0x75, 0x73, 0x65, 0x64, 0x42, 0x79, 0x74, 0x65, 0x73, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x09, 0x75, 0x73, 0x65, 0x64, 0x42, 0x79, 0x74, 0x65, 0x73, 0x12, 0x26, 0x0a,
	0x0e, 0x61, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x42, 0x79, 0x74, 0x65, 0x73, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0e, 0x61, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x6c, 0x65,
	0x42, 0x79, 0x74, 0x65, 0x73, 0x12, 0x28, 0x0a, 0x0f, 0x63, 0x61, 0x70, 0x61, 0x63, 0x69, 0x74,
	0x79, 0x50, 0x65, 0x72, 0x63, 0x65, 0x6e, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x02, 0x52, 0x0f,
	0x63, 0x61, 0x70, 0x61, 0x63, 0x69, 0x74, 0x79, 0x50, 0x65, 0x72, 0x63, 0x65, 0x6e, 0x74, 0x1a,
	0x7d, 0x0a, 0x13, 0x46, 0x69, 0x6c, 0x65, 0x53, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x49, 0x6e, 0x6f,
	0x64, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x1c, 0x0a, 0x09, 0x69, 0x6e, 0x6f, 0x64, 0x65, 0x55,
	0x73, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x69, 0x6e, 0x6f, 0x64, 0x65,
	0x55, 0x73, 0x65, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x69, 0x6e, 0x6f, 0x64, 0x65, 0x46, 0x72, 0x65,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x69, 0x6e, 0x6f, 0x64, 0x65, 0x46, 0x72,
	0x65, 0x65, 0x12, 0x2a, 0x0a, 0x10, 0x69, 0x6e, 0x6f, 0x64, 0x65, 0x55, 0x73, 0x65, 0x64, 0x50,
	0x65, 0x72, 0x63, 0x65, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x02, 0x52, 0x10, 0x69, 0x6e,
	0x6f, 0x64, 0x65, 0x55, 0x73, 0x65, 0x64, 0x50, 0x65, 0x72, 0x63, 0x65, 0x6e, 0x74, 0x32, 0xa3,
	0x01, 0x0a, 0x0f, 0x45, 0x78, 0x70, 0x6f, 0x72, 0x74, 0x65, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x12, 0x8f, 0x01, 0x0a, 0x13, 0x53, 0x65, 0x6e, 0x64, 0x53, 0x74, 0x72, 0x65, 0x61,
	0x6d, 0x53, 0x6e, 0x61, 0x70, 0x73, 0x68, 0x6f, 0x74, 0x73, 0x12, 0x28, 0x2e, 0x73, 0x79, 0x73,
	0x5f, 0x65, 0x78, 0x70, 0x6f, 0x72, 0x74, 0x65, 0x72, 0x2e, 0x53, 0x65, 0x6e, 0x64, 0x53, 0x74,
	0x72, 0x65, 0x61, 0x6d, 0x53, 0x6e, 0x61, 0x70, 0x73, 0x68, 0x6f, 0x74, 0x73, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x29, 0x2e, 0x73, 0x79, 0x73, 0x5f, 0x65, 0x78, 0x70, 0x6f, 0x72,
	0x74, 0x65, 0x72, 0x2e, 0x53, 0x65, 0x6e, 0x64, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x53, 0x6e,
	0x61, 0x70, 0x73, 0x68, 0x6f, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x21, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x1b, 0x22, 0x16, 0x2f, 0x73, 0x6e, 0x61, 0x70, 0x73, 0x68,
	0x6f, 0x74, 0x73, 0x2f, 0x73, 0x65, 0x6e, 0x64, 0x2d, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x3a,
	0x01, 0x2a, 0x30, 0x01, 0x42, 0x30, 0x5a, 0x2e, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63,
	0x6f, 0x6d, 0x2f, 0x68, 0x69, 0x68, 0x6f, 0x61, 0x6b, 0x2f, 0x6f, 0x74, 0x75, 0x73, 0x2d, 0x63,
	0x6f, 0x75, 0x72, 0x73, 0x65, 0x2d, 0x68, 0x77, 0x73, 0x2f, 0x73, 0x79, 0x73, 0x2d, 0x65, 0x78,
	0x70, 0x6f, 0x72, 0x74, 0x65, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_sys_exporter_SysExporter_proto_rawDescOnce sync.Once
	file_api_sys_exporter_SysExporter_proto_rawDescData = file_api_sys_exporter_SysExporter_proto_rawDesc
)

func file_api_sys_exporter_SysExporter_proto_rawDescGZIP() []byte {
	file_api_sys_exporter_SysExporter_proto_rawDescOnce.Do(func() {
		file_api_sys_exporter_SysExporter_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_sys_exporter_SysExporter_proto_rawDescData)
	})
	return file_api_sys_exporter_SysExporter_proto_rawDescData
}

var file_api_sys_exporter_SysExporter_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_api_sys_exporter_SysExporter_proto_goTypes = []interface{}{
	(*SendStreamSnapshotsRequest)(nil),                              // 0: sys_exporter.SendStreamSnapshotsRequest
	(*SendStreamSnapshotsResponse)(nil),                             // 1: sys_exporter.SendStreamSnapshotsResponse
	(*Snapshot)(nil),                                                // 2: sys_exporter.Snapshot
	(*Snapshot_LoadAverage)(nil),                                    // 3: sys_exporter.Snapshot.LoadAverage
	(*Snapshot_CpuUsage)(nil),                                       // 4: sys_exporter.Snapshot.CpuUsage
	(*Snapshot_DiskUsage)(nil),                                      // 5: sys_exporter.Snapshot.DiskUsage
	(*Snapshot_NetworkTopTalkers)(nil),                              // 6: sys_exporter.Snapshot.NetworkTopTalkers
	(*Snapshot_FileSystemInfo)(nil),                                 // 7: sys_exporter.Snapshot.FileSystemInfo
	(*Snapshot_NetworkTopTalkers_NetworkTalker)(nil),                // 8: sys_exporter.Snapshot.NetworkTopTalkers.NetworkTalker
	(*Snapshot_FileSystemInfo_FileSystem)(nil),                      // 9: sys_exporter.Snapshot.FileSystemInfo.FileSystem
	(*Snapshot_FileSystemInfo_FileSystem_FileSystemMemoryInfo)(nil), // 10: sys_exporter.Snapshot.FileSystemInfo.FileSystem.FileSystemMemoryInfo
	(*Snapshot_FileSystemInfo_FileSystem_FileSystemInodeInfo)(nil),  // 11: sys_exporter.Snapshot.FileSystemInfo.FileSystem.FileSystemInodeInfo
}
var file_api_sys_exporter_SysExporter_proto_depIdxs = []int32{
	2,  // 0: sys_exporter.SendStreamSnapshotsResponse.snapshot:type_name -> sys_exporter.Snapshot
	3,  // 1: sys_exporter.Snapshot.loadAverage:type_name -> sys_exporter.Snapshot.LoadAverage
	4,  // 2: sys_exporter.Snapshot.cpuUsage:type_name -> sys_exporter.Snapshot.CpuUsage
	5,  // 3: sys_exporter.Snapshot.diskUsage:type_name -> sys_exporter.Snapshot.DiskUsage
	6,  // 4: sys_exporter.Snapshot.networkTopTalkers:type_name -> sys_exporter.Snapshot.NetworkTopTalkers
	7,  // 5: sys_exporter.Snapshot.fileSystemInfo:type_name -> sys_exporter.Snapshot.FileSystemInfo
	8,  // 6: sys_exporter.Snapshot.NetworkTopTalkers.byBytesIn:type_name -> sys_exporter.Snapshot.NetworkTopTalkers.NetworkTalker
	8,  // 7: sys_exporter.Snapshot.NetworkTopTalkers.byBytesOut:type_name -> sys_exporter.Snapshot.NetworkTopTalkers.NetworkTalker
	9,  // 8: sys_exporter.Snapshot.FileSystemInfo.fileSystem:type_name -> sys_exporter.Snapshot.FileSystemInfo.FileSystem
	10, // 9: sys_exporter.Snapshot.FileSystemInfo.FileSystem.memoryInfo:type_name -> sys_exporter.Snapshot.FileSystemInfo.FileSystem.FileSystemMemoryInfo
	11, // 10: sys_exporter.Snapshot.FileSystemInfo.FileSystem.inodeInfo:type_name -> sys_exporter.Snapshot.FileSystemInfo.FileSystem.FileSystemInodeInfo
	0,  // 11: sys_exporter.ExporterService.SendStreamSnapshots:input_type -> sys_exporter.SendStreamSnapshotsRequest
	1,  // 12: sys_exporter.ExporterService.SendStreamSnapshots:output_type -> sys_exporter.SendStreamSnapshotsResponse
	12, // [12:13] is the sub-list for method output_type
	11, // [11:12] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_api_sys_exporter_SysExporter_proto_init() }
func file_api_sys_exporter_SysExporter_proto_init() {
	if File_api_sys_exporter_SysExporter_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_sys_exporter_SysExporter_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendStreamSnapshotsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_sys_exporter_SysExporter_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendStreamSnapshotsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_sys_exporter_SysExporter_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Snapshot); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_sys_exporter_SysExporter_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Snapshot_LoadAverage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_sys_exporter_SysExporter_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Snapshot_CpuUsage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_sys_exporter_SysExporter_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Snapshot_DiskUsage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_sys_exporter_SysExporter_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Snapshot_NetworkTopTalkers); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_sys_exporter_SysExporter_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Snapshot_FileSystemInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_sys_exporter_SysExporter_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Snapshot_NetworkTopTalkers_NetworkTalker); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_sys_exporter_SysExporter_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Snapshot_FileSystemInfo_FileSystem); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_sys_exporter_SysExporter_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Snapshot_FileSystemInfo_FileSystem_FileSystemMemoryInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_sys_exporter_SysExporter_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Snapshot_FileSystemInfo_FileSystem_FileSystemInodeInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_sys_exporter_SysExporter_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_sys_exporter_SysExporter_proto_goTypes,
		DependencyIndexes: file_api_sys_exporter_SysExporter_proto_depIdxs,
		MessageInfos:      file_api_sys_exporter_SysExporter_proto_msgTypes,
	}.Build()
	File_api_sys_exporter_SysExporter_proto = out.File
	file_api_sys_exporter_SysExporter_proto_rawDesc = nil
	file_api_sys_exporter_SysExporter_proto_goTypes = nil
	file_api_sys_exporter_SysExporter_proto_depIdxs = nil
}
